#!/bin/bash
# Current user
USERNAME=$(whoami)
# Current date
DATE=$(date +"%Y-%m-%d %H:%M:%S")
# System hostname
HOSTNAME=$(hostname)
# Os name and version
OS=$(. /etc/os-release && echo "$PRETTY_NAME")
# System uptime
Uptime=$(uptime -p)
# Cpu model
CPU=$(lscpu | grep 'Model name' | awk -F': ' '{print $2}' | sed 's/^ *//')
# RAM installed
RAM=$(free -h | awk '/^Mem:/ {print $2}')
# Disk information
DISKS=$(lsblk -d -o NAME,SIZE | grep -v "NAME" | awk '{print "Disk: " $1 " Size: " $2}')
# Video card model.
Video=$(lspci | grep -i vga | awk -F: '{print $3}' | sed 's/^ //')

# System FQDN 
FQDN=$(hostname -f)
# IP ADDRESS 
Host_Address=$(ip a | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | head -n 1)
# Gateway address.
Gateway_IP=$(ip r | grep default | awk '{print $3}')
# IP of DNS server
DNS_Server=$(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -n 1)
# Logged in user
Users_Logged_In=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')
# Free disk space
Disk_Space=$(df -h | awk '/^\/dev/ {print $6 " " $4}')
# Number of running processes.
Process_Count=$(ps -e | wc -l)
# System load
Avg_load=$(uptime | awk -F'average: ' '{print $2}')
# Listening ports
Listening_Ports=$(ss -tuln | awk '/LISTEN/ {print $5}' | cut -d':' -f2 | sort -n | uniq | tr '\n' ',' | sed 's/,$//')
# Firewall status
UFW_Status=$(sudo ufw status | grep -w "Status" | awk '{print $2}')


# Prints the system information
cat << EOF

System Report generated by $USERNAME, $DATE

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $Uptime

Hardware Information
--------------------
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $Video

Network Information
-------------------
FQDN: $FQDN
Host Address: $Host_Address
Gateway IP: $Gateway_IP
DNS Server: $DNS_Server

System Status
-------------
Users Logged In: $Users_Logged_In
Disk Space: $Disk_Space
Process Count: $Process_Count
Load Averages: $Avg_Load
Listening Network Ports: $Listening_Ports
UFW Status: $UFW_Status

EOF

