#!/bin/bash
# Clear the terminal screen
clear
# finds current user
USERNAME=$(whoami)
# finds the current date
DATE=$(date +"%Y-%m-%d %H:%M:%S")
# finds system host
HOSTNAME=$(hostname)
# finds os name and version
OS=$(. /etc/os-release && echo "$PRETTY_NAME")
# fnds uptime of the system
Uptime=$(uptime -p)
# finds cpu model
CPU=$(lscpu | grep 'Model name' | awk -F': ' '{print $2}' | sed 's/^ *//')
# finds total installed RAM
RAM=$(free -h | awk '/^Mem:/ {print $2}')
# finds disk information
DISKS=$(lsblk -d -o NAME,SIZE | grep -v "NAME" | awk '{print "Disk: " $1 " Size: " $2}')
# finds the video card model.
Video=$(lspci | grep -i vga | awk -F: '{print $3}' | sed 's/^ //')

# finds the FQDN of the system.
FQDN=$(hostname -f)
# finds the IP ADDRESS FOR THE INTERFACE THAT IS CONNECTED TO THE DEFAULT GATEWAY.
Host_Address=$(ip a | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | head -n 1)
# finds the Gateway address.
Gateway_IP=$(ip r | grep default | awk '{print $3}')
# finds the DNS server IP.
DNS_Server=$(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -n 1)
# finds who is logged in.
Users_Logged_In=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')
# finds free disk space for each partition.
Disk_Space=$(df -h | awk '/^\/dev/ {print $6 " " $4}')
# finds the total number of running processes.
Process_Count=$(ps -e | wc -l)
# find the load on the system.
Avg_load=$(uptime | awk -F'average: ' '{print $2}')
# finds the ports that are listening.
Listening_Ports=$(ss -tuln | awk '/LISTEN/ {print $5}' | cut -d':' -f2 | sort -n | uniq | tr '\n' ',' | sed 's/,$//')
# finds if the firewall is active or inactive.
UFW_Status=$(sudo ufw status | grep -w "Status" | awk '{print $2}')


# Prints the system information
cat << EOF

System Report generated by $USERNAME, $DATE

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $Uptime

Hardware Information
--------------------
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $Video

Network Information
-------------------
FQDN: $FQDN
Host Address: $Host_Address
Gateway IP: $Gateway_IP
DNS Server: $DNS_Server

System Status
-------------
Users Logged In: $Users_Logged_In
Disk Space: $Disk_Space
Process Count: $Process_Count
Load Averages: $Avg_Load
Listening Network Ports: $Listening_Ports
UFW Status: $UFW_Status

EOF

